### ISSUE TITLE
WOW (can close)

### ISSUE THREAD

**Issue by 007-JB** [shuckster/OBIS#11]
Sorry this not issue per say, its for feedback to authior of this OBIS app- simply HAD to say - AMAZING BRO! How cool is this - it's amazing - hoping we have CSV - just in the middle of using it - can't you do something for barclays too pls!     NICE!! 

Easy star - 5 if I could - yeahh!

Thanks a mil.  I love it.

**Comment by shuckster** [comment]
Hey, thank you for the kind words! Glad you found it useful.

It took a lot of messing about with my own HSBC account to get OBIS working as you see it. I say this because I don't have a Barclays account, so I'm unlikely to develop a plugin for it at this point.

Still, I'm open if someone wants to contribute a [plugin](https://github.com/shuckster/OBIS/tree/master/src/plugins)! :)
