### ISSUE TITLE
Obfuscated code

### ISSUE THREAD

**Issue by masterell** [shuckster/OBIS#4]
Appreciate the rewrite for this @shuckster. Just worried that with the new code being obfuscated, it's very difficult to see what's going on. Since this scrapes bank details, it would be good to be able to see what the code does.

Also, it's not immediately clear what page one should run the bookmarklet on.

**Comment by shuckster** [comment]
Good points @masterell . All non-obfuscated source lives in `src/`, and I put together a (very barebones!) [ARCH.md](https://github.com/shuckster/OBIS/blob/master/ARCH.md) document that describes the build-process for turning it into `dist/`.

Still, since the code is run from `dist/` it would indeed be a better default to leave it unobfuscated, especially as it deals with sensitive data.  I'll make a global `MINIFY_DIST` variable for that so we can easily toggle minification on-and-off.

Unfortunately, CORB may mean that OBIS needs to be [run locally](https://github.com/shuckster/OBIS#update--21st-march-2021) from now on. This is a bit of a pain, but it does mean that you have to download the full unobfuscated source before running it.

As for the page to run it on, it doesn't matter anymore. I usually run it just from the summary page.

**Comment by masterell** [comment]
Yes CORB does make this a bit more difficult for the average user. I'm not particularly familiar with Chrome Extensions, so not sure how portable this is, but would this not lend itself quite well to one?

**Comment by shuckster** [comment]
In addition to the obvious cross-browser problems this will invite, I guess the project will have to deal with the occasional breaking extension-API change. Still, it would be a considerable usability improvement if it can overcome the CORB issue.

I have thought many times about turning this into Chrome Extension. This might finally be the motivation to do it.

**Comment by shuckster** [comment]
@masterell - I have a WIP extension now in the `dist/` folder.

I've not added it to the Chrome Web Store yet, so if you'd like to try it out follow these steps:

1. Navigate to: `chrome://extensions/`
2. Enable `Developer mode`
3. Click `[ Load unpacked ]`
4. Choose the `dist/extension/` folder

The code is left unminified, same as the bookmarklet. The extension is integrated into the build-scripts and will be produced along with the bookmarklet if you'd like to DIY it.

Turns out there's a "Web Extensions" standard I wasn't aware of, and this means that it *should* work cross-browser. Unfortunately, while the UI loads in Firefox no statements will download, so it's Chrome-only for now.

**Comment by masterell** [comment]
@shuckster Truly superb. It's a really sorry state of events where someone has to write 12,000 lines of code just for functionality a bank like HSBC should be providing their customers with, but here we are I guess. Really appreciate all the effort and time that has gone into this. The Chrome extension is superb and I think would greatly help a lot of people. It would also appeal to less tech savvy users who may be put off by having to run a local server.

Just as a suggestion for future versions - the checkbox functionality in earlier versions to specify which statements are downloaded and in what formats was very helpful. Currently you download all the statements for a given time period (min 1 year) in every possible format. That said, what you've done here is faultless and I can assure you it's greatly appreciated.

**Comment by shuckster** [comment]
@masterell - I've managed to get the extension on the Chrome Web Store. I thought it would make sense to keep it "private" until it's tested. If you'd like to do that, let me know and I'll add your email to the testers list. There are no functionality changes, so no worries if you'd rather not.

**Comment by masterell** [comment]
@shuckster That's the most flabbergasting point of all - that OBIS merely makes an API request and processes the response. Yet all HSBC can offer their users is a lousy PDF statement. Having it available on the Chrome web store is a double edged sword. Yes on the one hand HSBC may notice it, but on the other hand - perhaps it'll wake then up and realise there is demand for it. Perhaps one day they'll even incorporate this functionality themselves! I've sent them enough emails on it.

Happy to be added to the tester list. Will have a play around when I get some time.

**Comment by shuckster** [comment]
Super, thank you. I'll add you to the tester list @masterell . I do hope the same as you, and that one day we won't need OBIS anymore. Fingers-crossed on that one!
